trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  acrName: princechatbotregistry
  imageTag: latest
  backendImage: $(acrName).azurecr.io/backend:$(imageTag)
  frontendImage: $(acrName).azurecr.io/frontend:$(imageTag)

steps:

- checkout: self

# Login to Azure
- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure-connection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az acr login --name $(acrName)

# Build Backend Image
- script: |
    docker build -t $(backendImage) ./backend
  displayName: Build Backend Image

# Push Backend Image
- script: |
    docker push $(backendImage)
  displayName: Push Backend Image

# Build Frontend Image
- script: |
    docker build -t $(frontendImage) ./frontend
  displayName: Build Frontend Image

# Push Frontend Image
- script: |
    docker push $(frontendImage)
  displayName: Push Frontend Image

# Deploy Backend
- task: AzureCLI@2
  displayName: Deploy Backend
  inputs:
    azureSubscription: 'azure-connection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az webapp config container set \
        --name prince-chatbot-backend \
        --resource-group ecommerce-chatbot-rg \
        --container-image-name $(backendImage)

# Deploy Frontend
- task: AzureCLI@2
  displayName: Deploy Frontend
  inputs:
    azureSubscription: 'azure-connection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az webapp config container set \
        --name prince-chatbot-app \
        --resource-group ecommerce-chatbot-rg \
        --container-image-name $(frontendImage)